name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependencias
        run: dotnet restore src/IronPeak.sln

      - name: Compilar solución
        run: dotnet build src/IronPeak.sln --configuration Release --no-restore
